version: '3.8'
services:
  postgresbd:
    image: postgres
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - 3306:3306
  app: 
    build: .
    depends_on:
      - postgresbd
    links:
      - postgresbd
    ports:
      - 3004:3004